services:
  db-verusen:
    image: 'postgres:latest'
    container_name: db-verusen
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./verusen.sql:/docker-entrypoint-initdb.d/verusen.sql

volumes:
  pgdata:
